### ISSUE TITLE
Multiple Range Filters

### ISSUE THREAD

**Issue by ashtonlance** [swiftype/swiftype-site-search-php#21]
I'm trying to run a query that on a field called `bookable_date`. I want to be able to return results that have a `bookable_date` in May and a `bookable_date` in July and not return results for the month of June.

Here's one of my approaches -- no results.
```
$args['bookable_date'] = array(
  "type"=> "or",
   "values"=> array(
      array(
       "type"=>"range",
          "from"=>'2019-01-01T00:00:00+00:00',
           "to"=> '2019-01-31T00:00:00+00:00',
         ),
          array (
            "type"=>"range",
             "from"=>'2019-05-01T00:00:00+00:00',
              "to"=> '2019-05-31T00:00:00+00:00',
             )
   )
  );
```

The `$args` variable is later passed to `$st_args` in the filters array. Which is then sent to Swiftype like this:
`$response = $client->search($engine , stripslashes($s), $st_args);`

**Comment by afoucret** [comment]
Hi @ashtonlance,

Unfortunately, the Site Search API does not allows using several range for the same fields.

Boolean semantics is only available for value filters:

```json
# Default behavior (OR filter)
{"filters": { "month": ["May", "July"] } }

# AND filter:
{"filters": { "month": { "type": "and", "values": ["May", "July"] } } }
```

The best option in you case would be to add 2 additional fields to your engine (`bookable_date_year` and `bookable_date_month` with the `enum` type) and then use the following filters:

```json
{
  "filters" : {
      "bookable_date_year": "2019",
      "bookable_date_month": ["May", "July"]
  }
}
```
This way you will be able to filter everything you want (a full year, several years, select arbitrary months, ...). 

Full documentation for filtering => https://swiftype.com/documentation/site-search/searching/filtering

**Comment by afoucret** [comment]
I close the issue for not being related to the client itself but to the Site Search API.

Feel free to contact our support team at support@swiftype.com if you have any more questions about the API.

**Comment by ashtonlance** [comment]
Gotcha. That makes total sense and seems to be a good work-around for us.

Thank you 💪
